# Generated by Django 3.0.5 on 2020-06-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0003_auto_20200618_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Client', verbose_name='Owner'),
        ),
    ]
