# Generated by Django 3.0.5 on 2020-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0007_auto_20200618_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(verbose_name='BroadCast Time'),
        ),
    ]
