# Generated by Django 3.0.5 on 2020-06-18 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0008_auto_20200618_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uid',
            field=models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel'),
        ),
    ]
