# Generated by Django 3.0.5 on 2020-06-18 17:28

import diya_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0011_auto_20200618_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_videothumb, verbose_name='Thumbnail'),
        ),
    ]
