# Generated by Django 3.0.5 on 2020-06-19 15:47

import diya_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0012_auto_20200618_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='add_1',
            field=models.CharField(default='0', max_length=50, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='add_2',
            field=models.CharField(default='0', max_length=50, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_channel_thumb, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='icon',
            field=models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_pgm_thumb, verbose_name='Thumbnail'),
        ),
    ]
