# Generated by Django 3.0.5 on 2020-07-01 11:13

import diya_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('uri', models.CharField(max_length=50, unique=True, verbose_name='URI')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprize', models.BooleanField(default=False, verbose_name='Enterprize Edition')),
                ('e_host', models.CharField(default='app.studentsonly.in', max_length=64, verbose_name='Enterprize Host')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_channel_thumb, verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, unique=True, verbose_name='Uri')),
                ('pub', models.BooleanField(default=True, verbose_name='Published Public')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('orderby', models.IntegerField(default=1000, verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Categories', verbose_name='Category')),
            ],
            options={
                'verbose_name': '1. Channel & School',
                'verbose_name_plural': '1. Channels & Schools',
                'ordering': ['orderby'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprize', models.BooleanField(default=False, verbose_name='Enterprize User')),
                ('quota', models.IntegerField(default=0, verbose_name='Enterprize Quota')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
                ('fname', models.CharField(max_length=32, verbose_name='First name')),
                ('lname', models.CharField(max_length=32, verbose_name='Last name')),
                ('add_1', models.CharField(default='0', max_length=50, verbose_name='Address Line 1')),
                ('add_2', models.CharField(default='0', max_length=50, verbose_name='Address Line 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(default=0, max_length=10, verbose_name='Mobile Number')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Staff Account')),
            ],
        ),
        migrations.CreateModel(
            name='EduzonePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.BooleanField(default=False, verbose_name='Custom Plan')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Plan Active')),
                ('name', models.CharField(max_length=50, verbose_name='Plan')),
                ('info', models.TextField(default=' ', verbose_name='Plan info')),
                ('validity', models.IntegerField(default='90', verbose_name='Validity')),
                ('price', models.IntegerField(default=0, verbose_name='Price :')),
                ('extra', models.IntegerField(default=10, verbose_name='Processing fee')),
                ('gst', models.IntegerField(default=18, verbose_name='GST Amount')),
                ('gst_type', models.IntegerField(default=18, verbose_name='GST(%)')),
                ('display_short', models.BooleanField(default=False, verbose_name='Temp Plan')),
                ('display_date', models.DateTimeField(blank=True, null=True, verbose_name='Temp Plan Expiry')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_videothumb, verbose_name='Thumbnail')),
                ('date', models.DateTimeField(verbose_name='BroadCast Time')),
                ('uri', models.CharField(max_length=64, verbose_name='Youtube vid')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
                ('banned', models.BooleanField(default=False, verbose_name='Content Banned')),
                ('demo', models.BooleanField(default=False, verbose_name='Demo Video (Sample)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='diya_api.Client', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Video/Topic/Lesson',
                'verbose_name_plural': 'Videos/Topics/Lesson',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField(default=True, verbose_name='Premium')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_pgm_thumb, verbose_name='Thumbnail')),
                ('uri', models.CharField(max_length=64, unique=True, verbose_name='Uri')),
                ('created', models.DateField(auto_now=True, verbose_name='Created On')),
                ('orderby', models.IntegerField(default=1000, verbose_name='Order')),
                ('custom_plan', models.BooleanField(default=False, verbose_name='Custom Plan')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='diya_api.Channel', verbose_name='Channel')),
                ('custom_plans', models.ManyToManyField(blank=True, to='diya_api.EduzonePlan', verbose_name='Custom Plans')),
            ],
            options={
                'verbose_name': '2. Class/Programme',
                'verbose_name_plural': '2. Classes/Programmes',
                'ordering': ['orderby', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('uri', models.CharField(max_length=64, unique=True, verbose_name='Uri')),
                ('orderby', models.IntegerField(default=1000, verbose_name='Order')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='diya_api.Programme', verbose_name='Programme')),
                ('video', models.ManyToManyField(related_name='playlist', to='diya_api.Video', verbose_name='Videos')),
            ],
            options={
                'verbose_name': '3. Subject/Playlist',
                'verbose_name_plural': '3. Subject/Playlists',
                'ordering': ['orderby'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Client', verbose_name='Owner/Client'),
        ),
    ]
