# Generated by Django 3.0.5 on 2020-06-20 08:49

import diya_api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_channel_thumb, verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
                ('pub', models.BooleanField(default=True, verbose_name='Published')),
                ('active', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': '1. Channel & School',
                'verbose_name_plural': '1. Channels & Schools',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
                ('fname', models.CharField(max_length=32, verbose_name='First name')),
                ('lname', models.CharField(max_length=32, verbose_name='Last name')),
                ('add_1', models.CharField(default='0', max_length=50, verbose_name='Address Line 1')),
                ('add_2', models.CharField(default='0', max_length=50, verbose_name='Address Line 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.IntegerField(default=0, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_videothumb, verbose_name='Thumbnail')),
                ('date', models.DateTimeField(verbose_name='BroadCast Time')),
                ('uri', models.CharField(max_length=64, verbose_name='Youtube vid')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
            ],
            options={
                'verbose_name': '4. Video/Topic/Lesson',
                'verbose_name_plural': '4. Videos/Topics/Lesson',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to=diya_api.models.path_and_rename_pgm_thumb, verbose_name='Thumbnail')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Channel', verbose_name='Channel')),
            ],
            options={
                'verbose_name': '2. Class/Programme',
                'verbose_name_plural': '2. Classes/Programmes',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Programme', verbose_name='Programme')),
                ('video', models.ManyToManyField(to='diya_api.Video', verbose_name='Videos')),
            ],
            options={
                'verbose_name': '3. Subject/Playlist',
                'verbose_name_plural': '3. Subject/Playlists',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Client', verbose_name='Owner'),
        ),
    ]
