# Generated by Django 3.0.5 on 2020-06-17 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.TextField(verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default=uuid.uuid4, editable=False, verbose_name='Channel')),
                ('fname', models.CharField(max_length=32, verbose_name='First name')),
                ('lname', models.CharField(max_length=32, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.IntegerField(default=0, max_length=10, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.TextField(verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.TextField(verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, verbose_name='Youtube vid')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Playlist', verbose_name='Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Description')),
                ('icon', models.TextField(verbose_name='Logo')),
                ('uri', models.CharField(max_length=64, verbose_name='Uri')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Channel', verbose_name='Channel')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='programme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Programme', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='channel',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Client', verbose_name='Owner'),
        ),
    ]
