# Generated by Django 3.0.5 on 2020-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.AddField(
            model_name='channel',
            name='pub',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(to='diya_api.Video', verbose_name='Videos'),
        ),
    ]
