# Generated by Django 3.0.5 on 2020-06-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['order'], 'verbose_name': '1. Channel & School', 'verbose_name_plural': '1. Channels & Schools'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['created', 'orderby'], 'verbose_name': '2. Class/Programme', 'verbose_name_plural': '2. Classes/Programmes'},
        ),
        migrations.AddField(
            model_name='programme',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Created On'),
        ),
        migrations.AddField(
            model_name='programme',
            name='orderby',
            field=models.IntegerField(default=1000, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Categories', verbose_name='Category'),
        ),
    ]
