# Generated by Django 3.0.5 on 2020-06-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0002_auto_20200617_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(null=True, to='diya_api.Video', verbose_name='Videos'),
        ),
    ]
