# Generated by Django 3.0.5 on 2020-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0002_auto_20200622_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['orderby'], 'verbose_name': '3. Subject/Playlist', 'verbose_name_plural': '3. Subject/Playlists'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['orderby', '-created'], 'verbose_name': '2. Class/Programme', 'verbose_name_plural': '2. Classes/Programmes'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='orderby',
            field=models.IntegerField(default=1000, verbose_name='Order'),
        ),
    ]
