# Generated by Django 3.0.5 on 2020-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0003_esubscibers'),
    ]

    operations = [
        migrations.AddField(
            model_name='esubscibers',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='esubscibers',
            name='details',
            field=models.TextField(default='', max_length=50, verbose_name='Details'),
        ),
    ]
