# Generated by Django 3.0.5 on 2020-06-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0003_auto_20200622_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['orderby'], 'verbose_name': '1. Channel & School', 'verbose_name_plural': '1. Channels & Schools'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='order',
            new_name='orderby',
        ),
    ]
