# Generated by Django 3.0.5 on 2020-07-04 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0004_auto_20200704_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uid',
            field=models.TextField(default=uuid.uuid4, editable=False, verbose_name='UID'),
        ),
    ]
