# Generated by Django 3.0.5 on 2020-06-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0004_auto_20200618_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.IntegerField(default=0, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(to='diya_api.Video', verbose_name='Videos'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
