# Generated by Django 3.0.5 on 2020-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0004_auto_20200622_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date'], 'verbose_name': '4. Video/Topic/Lesson', 'verbose_name_plural': '4. Videos/Topics/Lesson'},
        ),
        migrations.AddField(
            model_name='video',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Content Banned'),
        ),
    ]
