# Generated by Django 3.0.5 on 2020-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0005_auto_20200622_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
    ]
