# Generated by Django 3.0.5 on 2020-07-04 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0005_auto_20200704_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esubscibers',
            name='details',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='esubscibers',
            name='password',
            field=models.CharField(default='logitech', max_length=32, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='esubscibers',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, verbose_name='UID'),
        ),
    ]
