# Generated by Django 3.0.5 on 2020-06-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0005_auto_20200618_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '1. Channel & School', 'verbose_name_plural': '1. Channels & Schools'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': '3. Subject/Playlist', 'verbose_name_plural': '3. Subject/Playlists'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name': '2. Class/Programme', 'verbose_name_plural': '2. Classes/Programmes'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '4. Video/Topic/Lesson', 'verbose_name_plural': '4. Videos/Topics/Lesson'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='info',
        ),
        migrations.AddField(
            model_name='channel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
