# Generated by Django 3.0.5 on 2020-06-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0006_programme_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='demo',
            field=models.BooleanField(default=False, verbose_name='Demo Video (Sample)'),
        ),
    ]
