# Generated by Django 3.0.5 on 2020-07-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0006_auto_20200704_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='url')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='')),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Esubscibers', verbose_name='User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Video', verbose_name='Watched')),
            ],
            options={
                'verbose_name': 'Enterprise Subscriber Watch history',
                'verbose_name_plural': 'Enterprise Subscribers Watch history',
            },
        ),
        migrations.CreateModel(
            name='Elogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('datetime_text', models.TextField(blank=True, verbose_name='Date Time')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('ip', models.CharField(max_length=32, verbose_name='')),
                ('agent', models.TextField(blank=True, verbose_name='User Agents')),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diya_api.Esubscibers', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Enterprise Subscriber Login history',
                'verbose_name_plural': 'Enterprise Subscribers Login history',
            },
        ),
    ]
