# Generated by Django 3.0.5 on 2020-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0006_auto_20200618_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='uid',
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='BroadCast Time'),
        ),
    ]
