# Generated by Django 3.0.5 on 2020-06-22 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0007_video_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduzonePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.IntegerField(default=False, verbose_name='Custom Plan')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan')),
                ('validity', models.IntegerField(default='90', verbose_name='Validity')),
                ('price', models.IntegerField(default=0, verbose_name='Price :')),
                ('extra', models.IntegerField(default=10, verbose_name='Processing fee')),
                ('gst', models.IntegerField(default=18, verbose_name='GST Amount')),
                ('gst_type', models.IntegerField(default=18, verbose_name='GST(%)')),
                ('display_short', models.BooleanField(default=False, verbose_name='Temp Plan')),
                ('display_date', models.DateTimeField(blank=True, null=True, verbose_name='Temp Plan Expiry')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='custom_plan',
            field=models.IntegerField(default=False, verbose_name='Custom Plan'),
        ),
        migrations.AddField(
            model_name='programme',
            name='custom_plans',
            field=models.ManyToManyField(to='diya_api.EduzonePlan', verbose_name='Custom Plans'),
        ),
    ]
