# Generated by Django 3.0.5 on 2020-07-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0008_auto_20200709_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elogin',
            name='euser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='diya_api.Esubscibers', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='elogin',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='IP'),
        ),
    ]
