# Generated by Django 3.0.5 on 2020-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0008_auto_20200622_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='custom_plan',
            field=models.BooleanField(default=False, verbose_name='Custom Plan'),
        ),
    ]
