# Generated by Django 3.0.5 on 2020-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0009_video_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
