# Generated by Django 3.0.5 on 2020-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0009_auto_20200622_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduzoneplan',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Custom Plan'),
        ),
    ]
