# Generated by Django 3.0.5 on 2020-06-24 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0010_auto_20200622_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=50, verbose_name='ID'),
        ),
    ]
