# Generated by Django 3.0.5 on 2020-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0010_auto_20200618_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(blank=True, default='thumbnail_video.png', null=True, upload_to='e7b1e5bf-1cac-40d5-b4f5-a3f69e135b9d', verbose_name='Thumbnail'),
        ),
    ]
