# Generated by Django 3.0.5 on 2020-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0011_programme_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='custom_plans',
            field=models.ManyToManyField(blank=True, to='diya_api.EduzonePlan', verbose_name='Custom Plans'),
        ),
    ]
