# Generated by Django 3.0.5 on 2020-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0012_auto_20200624_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='uri',
            field=models.CharField(max_length=50, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='uri',
            field=models.CharField(max_length=64, unique=True, verbose_name='Uri'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='uri',
            field=models.CharField(max_length=64, unique=True, verbose_name='Uri'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='uri',
            field=models.CharField(max_length=64, unique=True, verbose_name='Uri'),
        ),
    ]
