# Generated by Django 3.0.5 on 2020-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0013_auto_20200624_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uri',
            field=models.CharField(max_length=64, verbose_name='Youtube vid'),
        ),
    ]
