# Generated by Django 3.0.5 on 2020-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0014_auto_20200624_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduzoneplan',
            name='info',
            field=models.TextField(default=' ', verbose_name='Plan info'),
        ),
    ]
