# Generated by Django 3.0.5 on 2020-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0015_eduzoneplan_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduzoneplan',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Plan Active'),
        ),
    ]
