# Generated by Django 3.0.5 on 2020-06-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0016_eduzoneplan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='diya_api.Channel', verbose_name='Channel'),
        ),
    ]
