# Generated by Django 3.0.5 on 2020-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0017_auto_20200627_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='enterprize',
            field=models.BooleanField(default=False, verbose_name='Enterprize Edition'),
        ),
    ]
