# Generated by Django 3.0.5 on 2020-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0019_auto_20200628_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='e_host',
            field=models.CharField(default='app.studentsonly.in', max_length=64, verbose_name='Enterprize Host'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub',
            field=models.BooleanField(default=True, verbose_name='Published Public'),
        ),
    ]
