# Generated by Django 3.0.5 on 2020-06-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0020_auto_20200628_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diya_api.Client', verbose_name='Owner'),
        ),
    ]
