# Generated by Django 3.0.5 on 2020-06-28 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0025_auto_20200628_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='diya_api.Client', verbose_name='Owner/Client'),
        ),
    ]
