# Generated by Django 3.0.5 on 2020-06-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0026_auto_20200628_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='diya_api.Client', verbose_name='Owner'),
        ),
    ]
