# Generated by Django 3.0.5 on 2020-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0028_client_enterprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='userlimit',
            field=models.IntegerField(default=0, verbose_name='Enterprize Quota'),
        ),
        migrations.AlterField(
            model_name='client',
            name='enterprize',
            field=models.BooleanField(default=False, verbose_name='Enterprize User'),
        ),
    ]
