# Generated by Django 3.0.5 on 2020-06-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0030_auto_20200628_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(related_name='playlist', to='diya_api.Video', verbose_name='Videos'),
        ),
    ]
