# Generated by Django 3.0.5 on 2020-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0031_auto_20200629_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
