# Generated by Django 3.0.5 on 2020-06-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0032_video_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='diya_api.Programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='premium',
            field=models.BooleanField(default=True, verbose_name='Premium'),
        ),
    ]
