# Generated by Django 3.0.5 on 2020-07-01 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='Unique ID')),
                ('text', models.TextField(default='', verbose_name='Reply')),
                ('user', models.CharField(max_length=50, verbose_name='username')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date time')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='Unique ID')),
                ('text', models.TextField(default='', verbose_name='Reply')),
                ('user', models.CharField(default='', max_length=50, verbose_name='username')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Name')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date time')),
                ('reply', models.ManyToManyField(blank=True, related_name='comment', to='dashboard_admin.Replies', verbose_name='Replies')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='0', max_length=64, verbose_name='Unique ID')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Dislikes')),
                ('text', models.TextField(blank=True, default='', verbose_name='Content')),
                ('comment', models.ManyToManyField(blank=True, related_name='article', to='dashboard_admin.Comment', verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
