# Generated by Django 3.0.5 on 2020-06-29 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diya_api', '0033_auto_20200629_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esubscibers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='UID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eusers', to='diya_api.Client', verbose_name='Client')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esubscriber', to='diya_api.Programme', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
            },
        ),
    ]
