# Generated by Django 3.0.5 on 2020-07-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0005_auto_20200704_1324'),
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diya_api.Video', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='reply', to='dashboard_admin.Replies', verbose_name='Replies'),
        ),
    ]
