# Generated by Django 3.0.5 on 2020-06-30 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='Unique ID')),
                ('text', models.TextField(default='', verbose_name='Reply')),
                ('user', models.CharField(max_length=50, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.AlterModelOptions(
            name='esubscibers',
            options={'verbose_name': 'Enterprise Subscriber', 'verbose_name_plural': 'Enterprise Subscribers'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='Unique ID')),
                ('text', models.TextField(default='', verbose_name='Reply')),
                ('user', models.CharField(max_length=50, verbose_name='username')),
                ('reply', models.ManyToManyField(blank=True, null=True, related_name='comment', to='dashboard_admin.Replies', verbose_name='Replies')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='0', max_length=64, verbose_name='Unique ID')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Dislikes')),
                ('text', models.TextField(blank=True, default='', verbose_name='Content')),
                ('comment', models.ManyToManyField(related_name='article', to='dashboard_admin.Comment', verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
