# Generated by Django 3.0.5 on 2020-06-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0002_auto_20200630_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='article', to='dashboard_admin.Comment', verbose_name='Comments'),
        ),
    ]
