# Generated by Django 3.0.5 on 2020-06-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0003_auto_20200630_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article', to='dashboard_admin.Comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='comment', to='dashboard_admin.Replies', verbose_name='Replies'),
        ),
    ]
