# Generated by Django 3.0.5 on 2020-06-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diya_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduzonePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(default=uuid.uuid4, max_length=50, verbose_name='Payment ID')),
                ('razor_pay', models.CharField(blank=True, max_length=128, verbose_name='Payment ID')),
            ],
        ),
        migrations.CreateModel(
            name='EduzonePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan')),
                ('validity', models.IntegerField(default='90', verbose_name='Validity')),
                ('price', models.IntegerField(default=0, verbose_name='Price :')),
                ('extra', models.IntegerField(default=10, verbose_name='Processing fee')),
                ('gst', models.IntegerField(default=18, verbose_name='GST Amount')),
                ('gst_type', models.IntegerField(default=18, verbose_name='GST(%)')),
                ('display_short', models.BooleanField(default=False, verbose_name='Temp Plan')),
                ('display_date', models.DateTimeField(blank=True, null=True, verbose_name='Temp Plan Expiry')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberpaymentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('eduzone_pay', models.CharField(blank=True, max_length=128, verbose_name='Payment ID')),
                ('razor_pay', models.CharField(blank=True, max_length=128, verbose_name='Payment ID')),
                ('order_id', models.CharField(default=' ', max_length=128, verbose_name='Eduzone Order ID')),
                ('razor_id', models.CharField(default=' ', max_length=128, verbose_name='Razorpay Order ID')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Active')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='classroom.EduzonePlan', verbose_name='Plan')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='diya_api.Programme', verbose_name='Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('subscribed', models.ManyToManyField(related_name='subscribers', to='classroom.SubscriberpaymentList')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EduzoneOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Order Created')),
                ('order', models.CharField(default=0, max_length=128, verbose_name='Order ID')),
                ('status', models.BooleanField(default=False, verbose_name='Success')),
                ('razor_id', models.CharField(default=' ', max_length=128, verbose_name='Razorpay Order ID')),
                ('razor_status', models.CharField(default=' ', max_length=64, verbose_name='Razorpay Status')),
                ('razor_amount', models.IntegerField(default=0, verbose_name='Razorpay Amount')),
                ('razor_created', models.CharField(default=' ', max_length=50, verbose_name='Razorpay created')),
                ('paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Order Cancelled')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='classroom.EduzonePlan', verbose_name='Plan')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='diya_api.Programme', verbose_name='Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
