# Generated by Django 3.0.5 on 2020-07-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diya_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduzonePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Order Created')),
                ('pay', models.CharField(max_length=50, verbose_name='Payment ID')),
                ('razor_id', models.CharField(default=' ', max_length=128, verbose_name='Razorpay Order ID')),
                ('razor_pay', models.CharField(blank=True, max_length=128, verbose_name='Razorpay Payment ID')),
                ('razor_email', models.TextField(default='', verbose_name='Rozor Email')),
                ('razor_mobile', models.TextField(default='', verbose_name='Razor Mobile')),
                ('razor_amount', models.IntegerField(default=0, verbose_name='Razorpay Amount')),
                ('razor_sign', models.TextField(default='', verbose_name='Razor Sign')),
                ('razorpay_text', models.TextField(default='', verbose_name='Rozorpay Text')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('eduzone_order', models.CharField(blank=True, max_length=128, verbose_name='Order ID')),
                ('razor_pay', models.CharField(default=' ', max_length=128, verbose_name='Razorpay payment ID')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Active')),
                ('expiry', models.TextField(default='0', verbose_name='Plan Expiry')),
                ('validity', models.IntegerField(default=0, verbose_name='Validity')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='diya_api.EduzonePlan', verbose_name='Plan')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='diya_api.Programme', verbose_name='Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='0', max_length=10, verbose_name='Mobile No')),
                ('school', models.TextField(default=' ', verbose_name='School : ')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Esubscibers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=64, verbose_name='UID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eusers', to='diya_api.Client', verbose_name='Client')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esubscriber', to='diya_api.Programme', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Enterprise Subscriber',
                'verbose_name_plural': 'Enterprise Subscribers',
            },
        ),
        migrations.CreateModel(
            name='EduzoneOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Order Created')),
                ('order', models.CharField(default=0, max_length=128, verbose_name='Order ID')),
                ('status', models.BooleanField(default=False, verbose_name='Success')),
                ('razor_id', models.CharField(default=' ', max_length=128, verbose_name='Razorpay Order ID')),
                ('razor_status', models.CharField(default=' ', max_length=64, verbose_name='Razorpay Status')),
                ('razor_amount', models.IntegerField(default=0, verbose_name='Razorpay Amount')),
                ('razor_created', models.CharField(default=' ', max_length=50, verbose_name='Razorpay created')),
                ('paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Order Cancelled')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='diya_api.EduzonePlan', verbose_name='Plan')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='diya_api.Programme', verbose_name='Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
