# Generated by Django 3.0.5 on 2020-06-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0008_auto_20200622_2210'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduzoneorder',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='diya_api.EduzonePlan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='subscriberpaymentlist',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='diya_api.EduzonePlan', verbose_name='Plan'),
        ),
        migrations.DeleteModel(
            name='EduzonePlan',
        ),
    ]
