# Generated by Django 3.0.5 on 2020-07-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Esubscibers',
        ),
    ]
