# Generated by Django 3.0.5 on 2020-06-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200622_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='0', max_length=10, verbose_name='Mobile No'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(default=' ', verbose_name='School : '),
        ),
    ]
