# Generated by Django 3.0.5 on 2020-06-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200622_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Created'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_amount',
            field=models.IntegerField(default=0, verbose_name='Razorpay Amount'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_created',
            field=models.CharField(default=' ', max_length=50, verbose_name='Razorpay created'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_email',
            field=models.TextField(default='', verbose_name='Rozor Email'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_id',
            field=models.CharField(default=' ', max_length=128, verbose_name='Razorpay Order ID'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_mobile',
            field=models.TextField(default='', verbose_name='Razor Mobile'),
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razor_sign',
            field=models.TextField(default='', verbose_name='Razor Sign'),
        ),
        migrations.AlterField(
            model_name='eduzonepay',
            name='pay',
            field=models.CharField(max_length=50, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='eduzonepay',
            name='razor_pay',
            field=models.CharField(blank=True, max_length=128, verbose_name='Razorpay Payment ID'),
        ),
        migrations.DeleteModel(
            name='SubscriberpaymentList',
        ),
    ]
