# Generated by Django 3.0.5 on 2020-06-27 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diya_api', '0017_auto_20200627_0953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0004_auto_20200627_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('eduzone_order', models.CharField(blank=True, max_length=128, verbose_name='Order ID')),
                ('razor_pay', models.CharField(default=' ', max_length=128, verbose_name='Razorpay payment ID')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Active')),
                ('expiry', models.TextField(default='0', verbose_name='Plan Expiry')),
                ('validity', models.IntegerField(default=0, verbose_name='Validity')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='diya_api.EduzonePlan', verbose_name='Plan')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='diya_api.Programme', verbose_name='Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
