# Generated by Django 3.0.5 on 2020-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_subscriptionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduzonepay',
            name='razor_created',
        ),
        migrations.AddField(
            model_name='eduzonepay',
            name='razorpay_text',
            field=models.TextField(default='', verbose_name='Rozorpay Text'),
        ),
    ]
