# Generated by Django 3.0.5 on 2020-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200627_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlist',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
